create table if not exists public.daily_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  weight_lb numeric(6,2) not null check (weight_lb > 0),
  calories_eaten integer not null check (calories_eaten >= 0),
  whoop_calories_burned integer not null check (whoop_calories_burned >= 0),
  protein_g integer check (protein_g >= 0),
  steps integer check (steps >= 0),
  workout_type text not null default 'None',
  workout_minutes integer check (workout_minutes >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, entry_date)
);

alter table public.daily_entries enable row level security;

create policy "Users can read their own entries"
on public.daily_entries for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own entries"
on public.daily_entries for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own entries"
on public.daily_entries for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own entries"
on public.daily_entries for delete to authenticated
using ((select auth.uid()) = user_id);
